<a href="https://colab.research.google.com/github/Amit198181/JBVNL/blob/main/Copy_of_Python_model_to_perform_all_calculations_on_the_RS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving b.xlsx to b.xlsx
User uploaded file "b.xlsx" with length 82060 bytes

In [4]:
import pandas as pd

df = pd.read_excel("b.xlsx")
display(df.head())

,SI.No.,Particular,DS-1 (A),DS-1 (B),DS-2,DS-3,NDS-1,NDS-2,NDS-3,LTIS,LTIS-D,IAS-1,IAS-2,SS-1,SS-2,HT,Total,Unnamed: 17
0,NaN,Account Head,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,No of consumer\na)Registered,1796563.00,2728908.00,1770176.0,76947.0,130009.00,413537.0,50575.0,45067.00,12328.00,146237.0,3653.0,728.00,315.0,3438.0,7178481.00,NaN
2,,b) Effective,1337500.00,2099898.00,1344391.0,66153.0,106132.00,279913.0,41111.0,22339.00,4463.00,116515.0,2872.0,640.00,150.0,2658.0,5424735.00,NaN
3,,c)Connected Load (in KW/HP/KVA),1713853.72,2879212.56,2450499.9,520032.0,155227.25,620912.0,689416.0,1035893.62,39244.57,209212.5,31066.0,14695.93,39320.0,1600613.0,11999199.05,NaN
4,,d) No. of Running Meters,833095.00,1409875.00,855395.0,51188.0,47393.00,149160.0,23910.0,15739.00,2044.00,48866.0,1312.0,182.00,0.0,2609.0,3440768.00,NaN

In [12]:
# Select only the numerical columns
numerical_cols = df.select_dtypes(include=['number'])

# Calculate the sum for each numerical column
column_sums = numerical_cols.sum()

# Display the sums
display(column_sums)

DS-1 (A)       1.872509e+11
DS-1 (B)       2.509741e+11
DS-2           1.745712e+11
DS-3           6.900425e+10
NDS-1          6.131930e+09
NDS-2          3.998249e+10
NDS-3          5.051467e+10
LTIS           2.345172e+10
LTIS-D         7.648584e+09
IAS-1          6.654575e+09
IAS-2          8.967820e+08
SS-1           3.026748e+09
SS-2           3.968845e+09
HT             2.509306e+11
Total          1.075007e+12
Unnamed: 17    7.101524e+10
dtype: float64

In [11]:
display(df[['Particular', 'DS-1 (A)', 'DS-1 (B)', 'DS-2', 'DS-3', 'NDS-1', 'NDS-2', 'NDS-3', 'LTIS', 'LTIS-D', 'IAS-1', 'IAS-2', 'SS-1', 'SS-2', 'HT']])

,Particular,DS-1 (A),DS-1 (B),DS-2,DS-3,NDS-1,NDS-2,NDS-3,LTIS,LTIS-D,IAS-1,IAS-2,SS-1,SS-2,HT
0,Account Head,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No of consumer\na)Registered,1796563.00,2728908.00,1770176.0,76947.00,130009.00,413537.0,50575.0,45067.00,12328.00,146237.0,3653.0,728.00,315.0,3438.00
2,b) Effective,1337500.00,2099898.00,1344391.0,66153.00,106132.00,279913.0,41111.0,22339.00,4463.00,116515.0,2872.0,640.00,150.0,2658.00
3,c)Connected Load (in KW/HP/KVA),1713853.72,2879212.56,2450499.9,520032.00,155227.25,620912.0,689416.0,1035893.62,39244.57,209212.5,31066.0,14695.93,39320.0,1600613.00
4,d) No. of Running Meters,833095.00,1409875.00,855395.0,51188.00,47393.00,149160.0,23910.0,15739.00,2044.00,48866.0,1312.0,182.00,0.0,2609.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,Total Export -Net Metering,0.00,0.00,377595.0,520313.00,0.00,1794.0,258432.0,93520.00,0.00,0.0,0.0,0.00,0.0,586329.00
131,Total Import -Net Metering,0.00,0.00,149850.0,297669.40,0.00,894.0,69707.0,77546.00,0.00,0.0,0.0,0.00,0.0,92406.30
132,Total Net -Net Metering,0.00,0.00,227745.0,222643.60,0.00,900.0,188725.0,15974.00,0.00,0.0,0.0,0.00,0.0,493922.70
133,Net Metering (₹),0.00,0.00,865431.0,846045.45,0.00,3420.0,717155.0,60701.20,0.00,0.0,0.0,0.00,0.0,1876906.13

In [13]:
import sklearn

In [14]:
import pandas as pd

In [15]:
# Helper function to extract a value by variable name
def get_value(var_str, df):
    # Use the actual column names instead of numerical indices
    row = df[df['Particular'].str.contains(var_str, case=False, na=False)]
    return float(row['DS-1 (A)'].iloc[0]) if not row.empty else None

In [16]:
# Extract required variables
sale_of_energy = get_value('Total  Sale of Energy', df)
total_other_charges = get_value('Total Other Charges', df)
electricity_duty = get_value('Electricity duty', df)
subsidy = get_value('subsidy', df)
energy_sold = get_value('Total Quantity of Energy Sold', df)

In [17]:
# Compute ratios and metrics
revenue_per_unit = sale_of_energy / energy_sold if sale_of_energy and energy_sold else None
other_receipts_per_unit = total_other_charges / energy_sold if total_other_charges and energy_sold else None
electricity_duty_per_unit = electricity_duty / energy_sold if electricity_duty and energy_sold else None
subsidy_per_unit = subsidy / energy_sold if subsidy and energy_sold else None

total_receipts = sum([x for x in [sale_of_energy, total_other_charges, electricity_duty, subsidy] if x])
revenue_receipts_ratio = sale_of_energy / total_receipts if sale_of_energy and total_receipts else None
other_receipts_ratio = total_other_charges / total_receipts if total_other_charges and total_receipts else None
ed_receipts_ratio = electricity_duty / total_receipts if electricity_duty and total_receipts else None
subsidy_receipts_ratio = subsidy / total_receipts if subsidy and total_receipts else None

In [10]:
# Print all results
print(f'Revenue per unit sold: {revenue_per_unit:.2f}')
print(f'Other Receipts per unit sold: {other_receipts_per_unit:.2f}')
print(f'Electricity duty per unit sold: {electricity_duty_per_unit:.2f}')
print(f'Subsidy per unit sold: {subsidy_per_unit:.2f}')
print(f'Revenue-to-total Receipts Ratio: {revenue_receipts_ratio:.2%}')
print(f'Other Receipts-to-total Receipts Ratio: {other_receipts_ratio:.2%}')
print(f'Electricity Duty-to-total Receipts Ratio: {ed_receipts_ratio:.2%}')
print(f'Subsidy-to-total Receipts Ratio: {subsidy_receipts_ratio:.2%}')

Revenue per unit sold: 7.13
Other Receipts per unit sold: 0.31
Electricity duty per unit sold: 0.36
Subsidy per unit sold: 0.86
Revenue-to-total Receipts Ratio: 82.33%
Other Receipts-to-total Receipts Ratio: 3.60%
Electricity Duty-to-total Receipts Ratio: 4.17%
Subsidy-to-total Receipts Ratio: 9.90%

In [ ]:
revenue_per_unit = sale_of_energy / energy_sold if sale_of_energy and energy_sold else None # explainations

In [ ]:
revenue_per_unit = sale_of_energy / energy_sold if sale_of_energy and energy_sold else None

In [ ]:
total_other_charges = get_value('Total Other Charges', df)

In [ ]:
difference = sale_of_energy - total_other_charges
print(f'The difference between sale_of_energy and total_other_charges is: {difference:.2f}')

The difference between sale_of_energy and total_other_charges is: 3065366850.96

In [ ]:
energy_sold = get_value('Total Quantity of Energy Sold', df)

In [ ]:
revenue_receipts_ratio = sale_of_energy / total_receipts if sale_of_energy and total_receipts else None

In [ ]:
other_receipts_per_unit = total_other_charges / energy_sold if total_other_charges and energy_sold else None

In [ ]:
electricity_duty_per_unit = electricity_duty / energy_sold if electricity_duty and energy_sold else None

In [ ]:
subsidy_per_unit = subsidy / energy_sold if subsidy and energy_sold else None

In [ ]:
total_receipts = sum([x for x in [sale_of_energy, total_other_charges, electricity_duty, subsidy] if x])

In [ ]:
energy_sold = get_value('Total Quantity of Energy Sold', df)

In [ ]:
total_other_charges = get_value('Total Other Charges', df)